rm test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.0 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.2 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.4 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.6 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.8 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5
python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 1 --render-step 1 --load-weightfile test_line_dqn/linedqn-2/weights_10000.h5 --save-trajectory test_line_dqn/traj-2_mix.h5

#rm test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.0 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.2 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.4 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.6 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 0.8 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
#python -B oo_dqn.py Line --model LineModel --mode test --learning-rate 0.0025 --target-network-update 200 --egreedy-final 0.01 --egreedy-decay 0.999 --replay-start-size 1000 --replay-buffer-size 0 --batch-size 64 --update-frequency 1 --max-step 2000 --test-epsilon 1 --render-step 1 --load-weightfile test_line_dqn/linedqn-1/weights_5000.h5 --save-trajectory test_line_dqn/traj-1_mix.h5
